/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Andrew Unsworth
 */

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author Andrew Unsworth
 */



public class UNSCORules extends javax.swing.JFrame {
    
    /**
     * Creates new form UNSCORules
     */
    public UNSCORules() {
        super("UNSCO Shopping Basket Analyser");
             
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFilePanel = new javax.swing.JPanel();
        btnOpenFile = new javax.swing.JButton();
        pathField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlRulesPanel = new javax.swing.JPanel();
        btnGenRules = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scroller = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        rulesTable = new javax.swing.JTable();
        btnExitApp = new javax.swing.JButton();
        logoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fileMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        openFileMenuItem = new javax.swing.JMenuItem();
        exitAppMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));

        pnlFilePanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlFilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Open A File", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 153, 0))); // NOI18N

        btnOpenFile.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnOpenFile.setText("Open File");
        btnOpenFile.setToolTipText("Click this button to select a file to analyse for association rules.");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        pathField.setEditable(false);
        pathField.setText("No file selected");
        pathField.setToolTipText("The file you've selected to open will appear here. Click the Generate Rules button to use this file to generate rules.");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Click the Open File Button to select a file to analyse. The file path and file name will apear in the text field below. ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Once the file is selected, press the Genereate Rules button to analyse the contents of the file.");

        javax.swing.GroupLayout pnlFilePanelLayout = new javax.swing.GroupLayout(pnlFilePanel);
        pnlFilePanel.setLayout(pnlFilePanelLayout);
        pnlFilePanelLayout.setHorizontalGroup(
            pnlFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilePanelLayout.createSequentialGroup()
                        .addComponent(btnOpenFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pathField))
                    .addGroup(pnlFilePanelLayout.createSequentialGroup()
                        .addGroup(pnlFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFilePanelLayout.setVerticalGroup(
            pnlFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pnlFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pathField)
                    .addComponent(btnOpenFile))
                .addContainerGap())
        );

        pnlRulesPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlRulesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Association Rules", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 153, 0))); // NOI18N

        btnGenRules.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnGenRules.setText("Generate Rules");
        btnGenRules.setToolTipText("Clcik this button to generate association rules.");
        btnGenRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenRulesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Click the Generate Rules button to perform market basket analysis on the file you've selected. ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("The results will appear in the text area below. Rules can be selected and copied for use elsewhere.");

        rulesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Premise", "Premise Support", "Consequence", "Consequence Support", "Confidence", "Lift", "Leverage", "Conviction"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rulesTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(rulesTable);

        scroller.setViewportView(jScrollPane1);

        javax.swing.GroupLayout pnlRulesPanelLayout = new javax.swing.GroupLayout(pnlRulesPanel);
        pnlRulesPanel.setLayout(pnlRulesPanelLayout);
        pnlRulesPanelLayout.setHorizontalGroup(
            pnlRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroller)
                    .addGroup(pnlRulesPanelLayout.createSequentialGroup()
                        .addComponent(btnGenRules)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 322, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRulesPanelLayout.setVerticalGroup(
            pnlRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenRules)
                    .addGroup(pnlRulesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(17, 17, 17)
                .addComponent(scroller, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExitApp.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnExitApp.setText("Exit Application");
        btnExitApp.setToolTipText("Click this button to close the application.");
        btnExitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitAppActionPerformed(evt);
            }
        });

        logoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 74)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("UNSCO Superstores");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Never Knowingly Paid Enough");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FileMenu.setText("File");

        openFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openFileMenuItem.setText("Open File");
        openFileMenuItem.setToolTipText("Open a file that contains data from which to create rules.");
        openFileMenuItem.setActionCommand("OpenFile");
        openFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(openFileMenuItem);

        exitAppMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exitAppMenuItem.setText("Exit Application");
        exitAppMenuItem.setToolTipText("Clcik this to close this utility.");
        exitAppMenuItem.setName("btnCloseApp"); // NOI18N
        exitAppMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAppMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(exitAppMenuItem);

        fileMenuBar.add(FileMenu);

        setJMenuBar(fileMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRulesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(btnExitApp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 27, Short.MAX_VALUE)
                .addComponent(pnlFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlRulesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExitApp)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitAppMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAppMenuItemActionPerformed
        exitApplication();
    }//GEN-LAST:event_exitAppMenuItemActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        openFile();        
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void btnGenRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenRulesActionPerformed
        try {
            buildRulesTable();
        } catch (Exception ex) {
            Logger.getLogger(UNSCORules.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Exception occurred: " + ex.toString());
        }
    }//GEN-LAST:event_btnGenRulesActionPerformed

    private void btnExitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitAppActionPerformed
        exitApplication();
    }//GEN-LAST:event_btnExitAppActionPerformed

    private void openFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileMenuItemActionPerformed
        openFile();
    }//GEN-LAST:event_openFileMenuItemActionPerformed

    private void exitApplication() {
        System.exit(0);
    }
    
    private void openFile() throws NullPointerException {
        /* Uses an IBFileDialog to get the filepath of the file to open.
           Then it sets the text of the path textfield to the path selected
           with the IBFileDialog.
        */
        try {
            IBFileDialog filer = new IBFileDialog();
            pathToFile = filer.open();
        
            pathField.setText(pathToFile);
        } catch (NullPointerException npe) {
            String message = new String("No file selected.");
            pathField.setText(message);
            System.out.println("NullPointerException occurred: " + message);
        }
        
    }
    
    private void buildRulesTable() throws Exception, IOException {
       
       // Check that filePath isn't an empty string so that there's a file to send to Weka
       if(pathToFile.equals("")) {
           System.out.println("No file selected.");
           return;
       }
    
       
        
       // Create a BasketAnalyser object to send a file to Weka for analysis
       BasketAnalyser analyser = new BasketAnalyser();
       
       // create a new two-dimensional Object array to store the rules returned by Weka
       Object[][] rules = new Object[10][8];
       
       // get the rules from Weka
       try {
            // assign the returned rules Stirng array to a new Sting array
            rules = analyser.getRules(pathToFile);
            } catch(IOException iox) {
                    String message = new String("File selected either incompatible with UNSCO Rule Generator or has no data in it.");
                    pathField.setText(message);
                    System.out.println(message);
                    return;
                    } catch (Exception e) {
                        System.out.println("Exception occurred: " + e.toString());
                    }
          
        // update the table with the new rules
        rulesTable.setModel(new javax.swing.table.DefaultTableModel(
            rules, columnNames));
        }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UNSCORules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UNSCORules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UNSCORules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UNSCORules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UNSCORules().setVisible(true);
            }
        });
    }

    // Non-UI declarations
    
    private static String pathToFile = new String("");
    private Object[] columnNames = {"Premise",
                                        "Premise Support",
                                        "Consequence",
                                        "Consequence Support",
                                        "Confidence",
                                        "Lift",
                                        "Leverage",
                                        "Conviction"};
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JButton btnExitApp;
    private javax.swing.JButton btnGenRules;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JMenuItem exitAppMenuItem;
    private javax.swing.JMenuBar fileMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JMenuItem openFileMenuItem;
    private javax.swing.JTextField pathField;
    private javax.swing.JPanel pnlFilePanel;
    private javax.swing.JPanel pnlRulesPanel;
    private javax.swing.JTable rulesTable;
    private javax.swing.JScrollPane scroller;
    // End of variables declaration//GEN-END:variables
}
